language: csharp
solution: WeihanLi.AspNetMvc.AccessControlHelper.sln
# runtime config
mono: none
dotnet: 2.0.0
dist: trusty

install:
  - dotnet --info
  - dotnet restore ./src/WeihanLi.AspNetMvc.AccessControlHelper/WeihanLi.AspNetMvc.AccessControlHelper.csproj
  
script:
  - dotnet build /p:Configuration=Release --framework:netstandard2.0 ./src/WeihanLi.AspNetMvc.AccessControlHelper/WeihanLi.AspNetMvc.AccessControlHelper.csproj